{"name": "test_invalid_login[incorrectUser-Password123-Incorrect login]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nassert 'Your username is invalid!' == 'Incorrect login'\n  \n  - Incorrect login\n  + Your username is invalid!", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"168afc3d1f44485d99d5b8f0bada7443\")>\nlogin_elements = (<selenium.webdriver.remote.webelement.WebElement (session=\"168afc3d1f44485d99d5b8f0bada7443\", element=\"f.C7701506E800...afc3d1f44485d99d5b8f0bada7443\", element=\"f.C7701506E80028F930A46AD06A71F52D.d.B971845A262351AD578D29918018B1DD.e.27\")>)\nusername_input = 'incorrectUser', password_input = 'Password123', expected_message = 'Incorrect login'\n\n    @pytest.mark.negative\n    @pytest.mark.parametrize(\"username_input, password_input, expected_message\", [\n        (\"incorrectUser\", \"Password123\", \"Incorrect login\"),  # Test incorrect username\n        (\"student\", \"123\", \"Your password is invalid!\"),     # Test incorrect password\n        (\"incorrectUser\", \"123\", \"Your username is invalid!\")  # Test both incorrect\n    ])\n    def test_invalid_login(driver, login_elements, username_input, password_input, expected_message):\n        username, password, submit = login_elements\n        username.send_keys(username_input)\n        password.send_keys(password_input)\n        submit.click()\n    \n        pop_up = WebDriverWait(driver, 5).until(\n            EC.visibility_of_element_located((By.XPATH, '/html/body/div[1]/div/section/section/div[2]'))\n        )\n        pop_up_message = pop_up.text\n>       assert pop_up_message == expected_message, f\"Expected '{expected_message}', but got '{pop_up_message}'\"\nE       AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nE       assert 'Your username is invalid!' == 'Incorrect login'\nE         \nE         - Incorrect login\nE         + Your username is invalid!\n\nlogin_page.py:85: AssertionError"}, "parameters": [{"name": "username_input", "value": "'incorrectUser'"}, {"name": "password_input", "value": "'Password123'"}, {"name": "expected_message", "value": "'Incorrect login'"}], "start": 1740491224690, "stop": 1740491225418, "uuid": "8e746dcd-5000-4cc9-a686-445e2bd7b505", "historyId": "3896d7a44dd642a9c2b0119d1f4b3723", "testCaseId": "6674ddf48017f312a808400bc8fd64ec", "fullName": "login_page#test_invalid_login", "labels": [{"name": "tag", "value": "negative"}, {"name": "suite", "value": "login_page"}, {"name": "host", "value": "MyPC"}, {"name": "thread", "value": "15444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_page"}]}